FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование приложения
COPY app/ .

# Переменные окружения
ENV STUDENT_NAME="Федоськина Виктория Эдуардовна"
ENV STUDENT_GROUP="БИСТ-22-ИТ-2"
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Порт приложения
EXPOSE 5000

# Запуск через Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "app:app"]